name: Sync Forked Repository

on:
  schedule:
    - cron: '0 * * * *'  # Execute a cada hora
  push:
    branches:
      - main  # Substitua pela branch principal do repositório original

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Forked Repository
        uses: actions/checkout@v2
        with:
          repository: <your-username>/<your-forked-repo>
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Add Original Repository as Upstream
        run: git remote add upstream https://github.com/HackyOff/<original-repo>.git

      - name: Fetch Upstream
        run: git fetch upstream

      - name: Merge Upstream Changes
        run: git merge upstream/main  # Substitua pela branch principal do repositório original

      - name: Push Changes
        run: git push origin main  # Substitua pela branch principal do seu repositório forked
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
